import api from './api.js';
export const dashboardService = { get: () => api.get('/dashboard/me') };
export const profileService = { mine: () => api.get('/profiles/me'), public: (slug) => api.get(`/profiles/${slug}`), update: (data) => api.patch('/profiles/me', data), visibility: (visibility) => api.patch('/profiles/me/visibility', { visibility }), template: (template) => api.patch('/profiles/me/template', { template }), skills: (skills) => api.put('/profiles/me/skills', { skills }), add: (section, data) => api.post(`/profiles/me/${section}`, data), remove: (section, id) => api.delete(`/profiles/me/${section}/${id}`) };
export const cardService = { mine: () => api.get('/cards/me'), public: (slug) => api.get(`/cards/${slug}`), update: (data) => api.patch('/cards/me', data) };
export const connectionService = { list: (params) => api.get('/connections', { params }), requests: () => api.get('/connections/requests'), sent: () => api.get('/connections/sent'), send: (userId) => api.post(`/connections/${userId}`), accept: (id) => api.patch(`/connections/${id}/accept`), reject: (id) => api.patch(`/connections/${id}/reject`), remove: (id) => api.delete(`/connections/${id}`) };
export const discoveryService = { discover: (params) => api.get('/discovery', { params }), search: (params) => api.get('/discovery/search', { params }), recordView: (id) => api.post(`/discovery/views/${id}`), recent: () => api.get('/discovery/views/recent'), analytics: () => api.get('/discovery/views/analytics') };
export const messageService = { conversations: () => api.get('/messages/conversations'), messages: (id) => api.get(`/messages/conversations/${id}`), send: (recipientId, content) => api.post('/messages', { recipientId, content }), reply: (id, content) => api.post(`/messages/conversations/${id}/messages`, { content }) };
export const engagementService = { feed: () => api.get('/engagement/thoughts/feed'), create: (data) => api.post('/engagement/thoughts', data), remove: (id) => api.delete(`/engagement/thoughts/${id}`), like: (id) => api.post(`/engagement/thoughts/${id}/like`), comments: (id) => api.get(`/engagement/thoughts/${id}/comments`), comment: (id, content) => api.post(`/engagement/thoughts/${id}/comments`, { content }) };
export const organizationService = { mine: () => api.get('/organizations/my'), get: (id) => api.get(`/organizations/${id}`), create: (data) => api.post('/organizations', data), update: (id, data) => api.patch(`/organizations/${id}`, data), departments: (id) => api.get(`/organizations/${id}/departments`), createDepartment: (id, data) => api.post(`/organizations/${id}/departments`, data), members: (id) => api.get(`/organizations/${id}/members`), addMember: (id, data) => api.post(`/organizations/${id}/members`, data), updateMemberRole: (id, memberId, role) => api.patch(`/organizations/${id}/members/${memberId}/role`, { role }), removeMember: (id, memberId) => api.delete(`/organizations/${id}/members/${memberId}`) };
